# Generated by Django 5.1 on 2024-09-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='Owner',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Venuw Owner'),
        ),
    ]
